// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuppyLove.Models;

namespace PuppyLove.Migrations
{
    [DbContext(typeof(PuppyLoveContext))]
    [Migration("20210125215750_MoreDogs")]
    partial class MoreDogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PuppyLove.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Location");

                    b.Property<string>("Mood")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OwnerName")
                        .IsRequired();

                    b.Property<string>("Size")
                        .IsRequired();

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 8,
                            Breed = "Mixed",
                            ImgUrl = "https://drive.google.com/file/d/12-NJjKT1mrCuA1lDzVCF9-1nec04oydw/view?usp=sharing",
                            Location = "Portland, OR",
                            Mood = "Upbeat and calm",
                            Name = "Helo",
                            OwnerName = "Dave",
                            Size = "Medium"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 2,
                            Breed = "Mixed",
                            ImgUrl = "https://photos.app.goo.gl/3sn4vdSiKDbLutba8",
                            Location = "Portland, OR",
                            Mood = "Snarky",
                            Name = "Bartleby",
                            OwnerName = "Sage",
                            Size = "Small"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 1,
                            Breed = "Husky",
                            ImgUrl = "https://share.icloud.com/photos/0mxrEdflh8fSsVDXz6QaL5X-A#Oak_Hills",
                            Location = "Portland, OR",
                            Mood = "Inquisitive, playful",
                            Name = "Fin",
                            OwnerName = "Jerrod",
                            Size = "Small"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 2,
                            Breed = "Mized",
                            ImgUrl = "",
                            Location = "Seattle, WA",
                            Mood = "Hyper and wild",
                            Name = "Jeans",
                            OwnerName = "Heather",
                            Size = "Medium"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 2,
                            Breed = "Great Pyrenees ",
                            ImgUrl = "https://photos.app.goo.gl/H8VkzPHeg1M6oWa38",
                            Location = "Portland, OR",
                            Mood = "Sweethearted goofus",
                            Name = "Remy",
                            OwnerName = "Marci",
                            Size = "Big"
                        },
                        new
                        {
                            DogId = 6,
                            Age = 12,
                            Breed = "Irish Setter",
                            ImgUrl = "https://photos.app.goo.gl/AqDXPTwJBJTzQP2s7",
                            Location = "Portland, OR",
                            Mood = "Loveable dunderhead",
                            Name = "Neville",
                            OwnerName = "Travis",
                            Size = "Large"
                        },
                        new
                        {
                            DogId = 7,
                            Age = 13,
                            Breed = "Belgian Shepard",
                            ImgUrl = "https://drive.google.com/file/d/1k-XzE-I0BPJK7RCZw0pfzIx0EO30IAEp/view?usp=sharing",
                            Location = "Portland, OR",
                            Mood = "Adorable old man",
                            Name = "Jasper",
                            OwnerName = "Erin",
                            Size = "Large"
                        },
                        new
                        {
                            DogId = 8,
                            Age = 11,
                            Breed = "Chihuaua",
                            ImgUrl = "https://photos.app.goo.gl/iBdKw2wsPtGdJjSL7",
                            Location = "Portland, OR",
                            Mood = "Sassy princess",
                            Name = "Truvie",
                            OwnerName = "Luke",
                            Size = "Tiny"
                        },
                        new
                        {
                            DogId = 9,
                            Age = 1,
                            Breed = "Corgi",
                            ImgUrl = "https://drive.google.com/file/d/1k-XzE-I0BPJK7RCZw0pfzIx0EO30IAEp/view?usp=sharing",
                            Location = "Portland, OR",
                            Mood = "High energy joy",
                            Name = "Opal",
                            OwnerName = "Sarah",
                            Size = "small"
                        },
                        new
                        {
                            DogId = 10,
                            Age = 3,
                            Breed = "German Sheppard",
                            ImgUrl = "https://photos.app.goo.gl/FbVEStTT3a198rua6",
                            Location = "Seaettle, WA",
                            Mood = "Anxious sweet boi",
                            Name = "Link",
                            OwnerName = "Kris",
                            Size = "Big"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
