// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuppyLove.Models;

namespace PuppyLove.Migrations
{
    [DbContext(typeof(PuppyLoveContext))]
    [Migration("20210125193718_SeedTest")]
    partial class SeedTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PuppyLove.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Location");

                    b.Property<string>("Mood")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OwnerName")
                        .IsRequired();

                    b.Property<string>("Size")
                        .IsRequired();

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 8,
                            Breed = "Mixed",
                            ImgUrl = "https://drive.google.com/file/d/12-NJjKT1mrCuA1lDzVCF9-1nec04oydw/view?usp=sharing",
                            Location = "Portland, OR",
                            Mood = "Upbeat and calm",
                            Name = "Helo",
                            OwnerName = "Dave",
                            Size = "Medium"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 2,
                            Breed = "Mixed",
                            ImgUrl = "https://photos.app.goo.gl/3sn4vdSiKDbLutba8",
                            Location = "Portland, OR",
                            Mood = "Snarky",
                            Name = "Bartleby",
                            OwnerName = "Sage",
                            Size = "Small"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
